<?php 
function get_woo_builder_get_placeholder_html( $behavior, $custom_url, $name ) {
    if ( $behavior === 'hide_placeholder' ) {
        return '';
    }

    if ( $behavior === 'custom_image' && ! empty( $custom_url ) ) {
        // Render the custom image
        return '<img src="' . esc_url( $custom_url ) . '" alt="' . esc_attr__( 'Placeholder', 'woo-builder' ) . '" class="category-placeholder custom-placeholder" />';
    }

    $icon_svg = '<svg viewBox="0 0 24 24" fill="currentColor" width="24" height="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M4 6h16v12H4zm2 2v8h12V8z"/></svg>'; 
    
    return '<div class="category-placeholder default-icon">' . $icon_svg . '<span>' . esc_html__( 'No Image Available', 'woo-builder' ) . '</span></div>';
}


/**
 * Destroys all transients generated by the WooCommerce Categories block.
 * This should be attached to hooks that signify a change in category data.
 */
function wbb_clear_category_transients() {
    $transient_base = 'wbb_woo_categories_';

    delete_transient( 'wbb_woo_categories_total_count' ); 
    $cache_keys_to_clear = [
        'wbb_woo_categories_base_query_hash1', 
    ];
    foreach ( $cache_keys_to_clear as $key ) {
        delete_transient( $key );
    }
    delete_transient( 'wbb_woo_categories_total_count' ); 
}

// Hooks when WooCommerce category data changes:
add_action( 'edited_product_cat', 'wbb_clear_category_transients' ); // Category updated
add_action( 'created_product_cat', 'wbb_clear_category_transients' ); // Category created
add_action( 'delete_product_cat', 'wbb_clear_category_transients' ); // Category deleted
add_action( 'woocommerce_after_product_object_save', 'wbb_clear_category_transients' ); // Product saved



// Prevent Duplicate Reviews
add_filter('preprocess_comment', function ($commentdata) {
    if ($commentdata['comment_type'] === 'review') {
        $exists = get_comments([
            'user_id' => get_current_user_id(),
            'post_id' => $commentdata['comment_post_ID'],
            'type'    => 'review',
            'count'   => true
        ]);

        if ($exists) {
            wp_die('You already reviewed this product.');
        }
    }
    return $commentdata;
});


// Purchase Verification
// add_filter('preprocess_comment', function ($commentdata) {
//     if ($commentdata['comment_type'] !== 'review') {
//         return $commentdata;
//     }

//     if (!wc_customer_bought_product(
//         wp_get_current_user()->user_email,
//         get_current_user_id(),
//         $commentdata['comment_post_ID']
//     )) {
//         wp_die('Only verified buyers can leave reviews.');
//     }

//     return $commentdata;
// });


/**
 * Apply a bundle discount by scanning the cart for products associated with the FBT block.
 */
add_action( 'woocommerce_cart_calculate_fees', 'mh_apply_bundle_discount', 10, 1 );

function mh_apply_bundle_discount( $cart ) {
    if ( is_admin() && ! defined( 'DOING_AJAX' ) ) {
        return;
    }


    $discount_percentage = 10; // Default 10%
    $target_bundle_count = 2;  // Min items to trigger discount

    // Check if we are on a single product page to try and grab block-specific attributes
    if ( is_product() ) {
        $post_id = get_the_ID();
        $content = get_post_field( 'post_content', $post_id );
        $blocks  = parse_blocks( $content );

        foreach ( $blocks as $block ) {
            if ( $block['blockName'] === 'woo-builder/woo-realeted-products' ) {
                if ( isset( $block['attrs']['discountPercentage'] ) ) {
                    $discount_percentage = intval( $block['attrs']['discountPercentage'] );
                }
                break;
            }
        }
    }

    $items_in_cart = $cart->get_cart_contents_count();

    if ( $items_in_cart >= $target_bundle_count && $discount_percentage > 0 ) {
        $subtotal = $cart->get_subtotal();
        $discount_amount = ( $subtotal * ( $discount_percentage / 100 ) ) * -1;


        $cart->add_fee( 
            sprintf( __( 'Bundle Savings (%d%%)', 'woo-builder' ), $discount_percentage ), 
            $discount_amount, 
            true 
        );
    }
}